import React, { useState, useEffect } from 'react';
import { Shield, FileText, CheckCircle, AlertTriangle, Lock } from 'lucide-react';

// ============================================
// TERMS OF SERVICE & NDA AGREEMENT COMPONENT
// Click-wrap implementation for Perennity Compliance Tool
// ============================================

const TERMS_VERSION = '1.0.0';
const TERMS_DATE = '2026-02-16';

const TermsContent = () => (
  <div className="prose prose-sm max-w-none text-slate-700">
    <p className="text-xs text-slate-500 mb-4">
      <strong>Version:</strong> {TERMS_VERSION} | <strong>Effective Date:</strong> {TERMS_DATE}
    </p>

    <h2 className="text-lg font-bold text-slate-800 mt-6 mb-3">TERMS OF SERVICE AND CONFIDENTIALITY AGREEMENT</h2>
    
    <p className="mb-4">
      This Terms of Service and Confidentiality Agreement ("<strong>Agreement</strong>") governs your access to and use of the Perennity Compliance Assessment Tool (the "<strong>Service</strong>") provided by Perennity Ltd ("<strong>Company</strong>", "<strong>we</strong>", "<strong>us</strong>", or "<strong>our</strong>").
    </p>
    
    <p className="mb-4">
      By accessing or using the Service, you ("<strong>User</strong>", "<strong>you</strong>", or "<strong>your</strong>") acknowledge that you have read, understood, and agree to be bound by this Agreement. If you do not agree to these terms, you must not use the Service.
    </p>

    <hr className="my-6 border-slate-200" />

    <h3 className="text-base font-bold text-slate-800 mt-6 mb-2">1. DEFINITIONS</h3>
    
    <p className="mb-2"><strong>1.1 "Confidential Information"</strong> means all information relating to the Service which the Company directly or indirectly discloses, or makes available, to you. This includes:</p>
    <ul className="list-disc pl-6 mb-4 space-y-1">
      <li>The methodology, algorithms, scoring systems, and assessment frameworks used by the Service;</li>
      <li>Any reports, analyses, recommendations, or outputs generated by the Service;</li>
      <li>Technical information, designs, trade secrets, and intellectual property of the Company;</li>
      <li>Business information, pricing, and operational processes of the Company.</li>
    </ul>

    <p className="mb-2"><strong>1.2 "User Data"</strong> means any data, information, or content that you input into, submit to, or provide through the Service.</p>

    <p className="mb-2"><strong>1.3 "Assessment Output"</strong> means any reports, scores, classifications, recommendations, or other outputs generated by the Service based on User Data.</p>

    <hr className="my-6 border-slate-200" />

    <h3 className="text-base font-bold text-slate-800 mt-6 mb-2">2. USER OBLIGATIONS AND DATA RESTRICTIONS</h3>

    <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-4">
      <p className="font-semibold text-amber-800 mb-2">⚠️ IMPORTANT: DATA USAGE RESTRICTIONS</p>
      <p className="text-amber-700 text-sm">You acknowledge and agree that you shall NOT input, upload, or submit any of the following to the Service:</p>
    </div>

    <p className="mb-2"><strong>2.1</strong> You shall NOT input, submit, or provide through the Service:</p>
    <ul className="list-disc pl-6 mb-4 space-y-1">
      <li><strong>Personal Data:</strong> Any information relating to an identified or identifiable natural person, including but not limited to names, identification numbers, location data, email addresses, or any data protected under GDPR, UK Data Protection Act 2018, or equivalent data protection legislation;</li>
      <li><strong>Production Data:</strong> Live, real-time, or production business data from active operational systems;</li>
      <li><strong>Sensitive Commercial Information:</strong> Trade secrets, confidential financial data, or proprietary information belonging to third parties without proper authorisation;</li>
      <li><strong>Regulated Data:</strong> Any data subject to specific regulatory protection including health data, financial account data, or government-classified information;</li>
      <li><strong>Third-Party Confidential Information:</strong> Any information you are bound to keep confidential under agreements with third parties.</li>
    </ul>

    <p className="mb-4"><strong>2.2</strong> You represent and warrant that:</p>
    <ul className="list-disc pl-6 mb-4 space-y-1">
      <li>All User Data you provide consists only of anonymised, aggregated, or hypothetical project information suitable for assessment purposes;</li>
      <li>You have all necessary rights, permissions, and authorisations to provide the User Data to the Service;</li>
      <li>Your use of the Service complies with all applicable laws and regulations;</li>
      <li>You are authorised to accept this Agreement on behalf of your organisation, if applicable.</li>
    </ul>

    <p className="mb-4"><strong>2.3</strong> You shall indemnify, defend, and hold harmless the Company from any claims, losses, damages, liabilities, costs, and expenses (including legal fees) arising from or related to your breach of this Section 2.</p>

    <hr className="my-6 border-slate-200" />

    <h3 className="text-base font-bold text-slate-800 mt-6 mb-2">3. CONFIDENTIALITY OBLIGATIONS</h3>

    <p className="mb-2"><strong>3.1</strong> You undertake to the Company that you shall:</p>
    <ul className="list-disc pl-6 mb-4 space-y-1">
      <li>Keep the Confidential Information secret and confidential;</li>
      <li>Not use or exploit the Confidential Information in any way except for evaluating your own sustainability compliance position;</li>
      <li>Not directly or indirectly disclose or make available any Confidential Information to any third party without the Company's prior written consent;</li>
      <li>Establish and maintain adequate security measures to safeguard the Confidential Information from unauthorised access or use.</li>
    </ul>

    <p className="mb-4"><strong>3.2</strong> The confidentiality obligations in this Section 3 shall continue for a period of three (3) years from your last use of the Service.</p>

    <hr className="my-6 border-slate-200" />

    <h3 className="text-base font-bold text-slate-800 mt-6 mb-2">4. INTELLECTUAL PROPERTY</h3>

    <p className="mb-4"><strong>4.1</strong> All intellectual property rights in and to the Service, including the methodology, algorithms, user interface, documentation, and any Assessment Output formats, shall remain vested in the Company. Nothing in this Agreement grants you any licence or other rights in respect of such intellectual property except the limited right to use the Service for your own internal assessment purposes.</p>

    <p className="mb-4"><strong>4.2</strong> You retain ownership of your User Data. By using the Service, you grant the Company a non-exclusive, royalty-free licence to use anonymised and aggregated User Data for the purposes of improving the Service and generating industry benchmarks, provided such use does not identify you or your organisation.</p>

    <hr className="my-6 border-slate-200" />

    <h3 className="text-base font-bold text-slate-800 mt-6 mb-2">5. DISCLAIMERS AND LIMITATIONS OF LIABILITY</h3>

    <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-4">
      <p className="font-semibold text-red-800 mb-2">⚠️ IMPORTANT DISCLAIMERS</p>
    </div>

    <p className="mb-2"><strong>5.1 No Professional Advice.</strong> The Service provides general information and indicative assessments only. Assessment Outputs:</p>
    <ul className="list-disc pl-6 mb-4 space-y-1">
      <li>Do NOT constitute legal, financial, investment, regulatory, or professional advice;</li>
      <li>Do NOT guarantee compliance with any regulatory framework including SFDR, UK SDR, EU Taxonomy, or any other regulation;</li>
      <li>Do NOT replace the need for professional advisors, legal counsel, or regulatory consultation;</li>
      <li>Are indicative only and may not reflect current regulatory requirements.</li>
    </ul>

    <p className="mb-2"><strong>5.2 No Warranties.</strong> THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO:</p>
    <ul className="list-disc pl-6 mb-4 space-y-1">
      <li>Warranties of merchantability, fitness for a particular purpose, or non-infringement;</li>
      <li>Warranties that the Service will be uninterrupted, error-free, or secure;</li>
      <li>Warranties as to the accuracy, completeness, reliability, or timeliness of any Assessment Output;</li>
      <li>Warranties that the Service reflects current regulatory requirements or will achieve any particular regulatory outcome.</li>
    </ul>

    <p className="mb-2"><strong>5.3 Limitation of Liability.</strong></p>
    <ul className="list-disc pl-6 mb-4 space-y-1">
      <li>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE COMPANY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, REVENUE, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL;</li>
      <li>THE COMPANY'S TOTAL LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL NOT EXCEED THE AMOUNT YOU PAID TO THE COMPANY FOR THE SERVICE IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR ONE HUNDRED POUNDS (£100), WHICHEVER IS GREATER;</li>
      <li>THE COMPANY SHALL NOT BE LIABLE FOR ANY DAMAGES ARISING FROM YOUR BREACH OF SECTION 2 (USER OBLIGATIONS AND DATA RESTRICTIONS);</li>
      <li>THE COMPANY SHALL NOT BE LIABLE FOR ANY RELIANCE YOU PLACE ON ASSESSMENT OUTPUTS WITHOUT OBTAINING INDEPENDENT PROFESSIONAL ADVICE.</li>
    </ul>

    <p className="mb-4"><strong>5.4</strong> Nothing in this Agreement excludes or limits liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or any other liability that cannot be excluded or limited by applicable law.</p>

    <hr className="my-6 border-slate-200" />

    <h3 className="text-base font-bold text-slate-800 mt-6 mb-2">6. DATA PROCESSING</h3>

    <p className="mb-4"><strong>6.1</strong> You acknowledge that the Company may process User Data to provide the Service and generate Assessment Outputs. The Company's processing of any personal data shall be governed by the Company's Privacy Policy.</p>

    <p className="mb-4"><strong>6.2</strong> The Company may use anonymised and aggregated data derived from User Data for:</p>
    <ul className="list-disc pl-6 mb-4 space-y-1">
      <li>Generating industry benchmarks and comparative analyses;</li>
      <li>Improving and developing the Service;</li>
      <li>Research and statistical purposes.</li>
    </ul>

    <hr className="my-6 border-slate-200" />

    <h3 className="text-base font-bold text-slate-800 mt-6 mb-2">7. TERMINATION</h3>

    <p className="mb-4"><strong>7.1</strong> Either party may terminate this Agreement at any time. Upon termination, you shall cease using the Service and, upon request, destroy or return any Confidential Information in your possession.</p>

    <p className="mb-4"><strong>7.2</strong> Sections 2.3 (Indemnification), 3 (Confidentiality), 4 (Intellectual Property), 5 (Disclaimers and Limitations), and 8 (Governing Law) shall survive termination.</p>

    <hr className="my-6 border-slate-200" />

    <h3 className="text-base font-bold text-slate-800 mt-6 mb-2">8. GENERAL PROVISIONS</h3>

    <p className="mb-4"><strong>8.1 Entire Agreement.</strong> This Agreement constitutes the entire agreement between you and the Company regarding the Service.</p>

    <p className="mb-4"><strong>8.2 Amendments.</strong> The Company may modify this Agreement at any time. Continued use of the Service after modifications constitutes acceptance of the modified terms.</p>

    <p className="mb-4"><strong>8.3 Severability.</strong> If any provision of this Agreement is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.</p>

    <p className="mb-4"><strong>8.4 Governing Law.</strong> This Agreement shall be governed by and construed in accordance with the laws of England and Wales.</p>

    <p className="mb-4"><strong>8.5 Jurisdiction.</strong> The courts of England and Wales shall have exclusive jurisdiction to settle any dispute arising out of or in connection with this Agreement.</p>

    <hr className="my-6 border-slate-200" />

    <h3 className="text-base font-bold text-slate-800 mt-6 mb-2">9. CONTACT</h3>

    <p className="mb-4">For questions about this Agreement, please contact: <strong>legal@perennity.com</strong></p>

  </div>
);

// ============================================
// ACCEPTANCE MODAL COMPONENT
// ============================================

export const TermsAcceptanceModal = ({ onAccept, onDecline }) => {
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const [acceptedTerms, setAcceptedTerms] = useState(false);
  const [acceptedDataRestrictions, setAcceptedDataRestrictions] = useState(false);

  const handleScroll = (e) => {
    const element = e.target;
    const isAtBottom = element.scrollHeight - element.scrollTop <= element.clientHeight + 50;
    if (isAtBottom) {
      setHasScrolledToBottom(true);
    }
  };

  const canAccept = hasScrolledToBottom && acceptedTerms && acceptedDataRestrictions;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/80 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-3xl w-full max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-teal-600 to-emerald-600 px-6 py-5 text-white flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center">
              <Shield className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold">Terms of Service & Confidentiality Agreement</h2>
              <p className="text-teal-100 text-sm">Please read carefully before using the Compliance Assessment Tool</p>
            </div>
          </div>
        </div>

        {/* Scrollable Terms Content */}
        <div 
          className="flex-1 overflow-y-auto px-6 py-4 min-h-0"
          onScroll={handleScroll}
        >
          <TermsContent />
        </div>

        {/* Scroll Indicator */}
        {!hasScrolledToBottom && (
          <div className="px-6 py-2 bg-amber-50 border-t border-amber-200 flex-shrink-0">
            <p className="text-amber-700 text-sm text-center flex items-center justify-center gap-2">
              <AlertTriangle className="w-4 h-4" />
              Please scroll to the bottom to read the full agreement
            </p>
          </div>
        )}

        {/* Acceptance Section */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex-shrink-0 space-y-4">
          {/* Checkboxes */}
          <div className="space-y-3">
            <label className={`flex items-start gap-3 cursor-pointer ${!hasScrolledToBottom ? 'opacity-50' : ''}`}>
              <input
                type="checkbox"
                checked={acceptedTerms}
                onChange={(e) => setAcceptedTerms(e.target.checked)}
                disabled={!hasScrolledToBottom}
                className="mt-1 rounded border-slate-300 text-teal-600 focus:ring-teal-500 disabled:cursor-not-allowed"
              />
              <span className="text-sm text-slate-700">
                I have read, understood, and agree to be bound by the <strong>Terms of Service and Confidentiality Agreement</strong>.
              </span>
            </label>

            <label className={`flex items-start gap-3 cursor-pointer ${!hasScrolledToBottom ? 'opacity-50' : ''}`}>
              <input
                type="checkbox"
                checked={acceptedDataRestrictions}
                onChange={(e) => setAcceptedDataRestrictions(e.target.checked)}
                disabled={!hasScrolledToBottom}
                className="mt-1 rounded border-slate-300 text-teal-600 focus:ring-teal-500 disabled:cursor-not-allowed"
              />
              <span className="text-sm text-slate-700">
                I confirm that I will <strong>NOT</strong> input any personal data, production data, sensitive commercial information, or third-party confidential information into this Service.
              </span>
            </label>
          </div>

          {/* Buttons */}
          <div className="flex gap-3">
            <button
              onClick={onDecline}
              className="flex-1 px-6 py-3 border border-slate-300 rounded-xl text-slate-700 font-medium hover:bg-slate-100 transition-colors"
            >
              Decline
            </button>
            <button
              onClick={() => {
                if (canAccept) {
                  // Store acceptance
                  localStorage.setItem('perennity_terms_accepted', JSON.stringify({
                    version: TERMS_VERSION,
                    acceptedAt: new Date().toISOString(),
                    acceptedTerms: true,
                    acceptedDataRestrictions: true
                  }));
                  onAccept();
                }
              }}
              disabled={!canAccept}
              className={`flex-1 px-6 py-3 rounded-xl font-medium transition-colors flex items-center justify-center gap-2 ${
                canAccept 
                  ? 'bg-gradient-to-r from-teal-600 to-emerald-600 text-white hover:from-teal-700 hover:to-emerald-700' 
                  : 'bg-slate-200 text-slate-400 cursor-not-allowed'
              }`}
            >
              <CheckCircle className="w-5 h-5" />
              Accept & Continue
            </button>
          </div>

          <p className="text-xs text-slate-500 text-center">
            By clicking "Accept & Continue", you are entering into a legally binding agreement.
          </p>
        </div>
      </div>
    </div>
  );
};

// ============================================
// TERMS CHECK WRAPPER COMPONENT
// ============================================

export const TermsGate = ({ children }) => {
  const [hasAccepted, setHasAccepted] = useState(null); // null = loading, true/false = checked
  const [showDeclineMessage, setShowDeclineMessage] = useState(false);

  useEffect(() => {
    // Check if user has already accepted current terms version
    const stored = localStorage.getItem('perennity_terms_accepted');
    if (stored) {
      try {
        const acceptance = JSON.parse(stored);
        if (acceptance.version === TERMS_VERSION && acceptance.acceptedTerms && acceptance.acceptedDataRestrictions) {
          setHasAccepted(true);
          return;
        }
      } catch (e) {
        // Invalid stored data, require re-acceptance
      }
    }
    setHasAccepted(false);
  }, []);

  const handleAccept = () => {
    setHasAccepted(true);
  };

  const handleDecline = () => {
    setShowDeclineMessage(true);
  };

  // Loading state
  if (hasAccepted === null) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 to-teal-50">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-teal-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-slate-600">Loading...</p>
        </div>
      </div>
    );
  }

  // Decline message
  if (showDeclineMessage) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 to-teal-50 p-4">
        <div className="bg-white rounded-2xl shadow-xl max-w-md w-full p-8 text-center">
          <div className="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-4">
            <Lock className="w-8 h-8 text-red-600" />
          </div>
          <h2 className="text-xl font-bold text-slate-800 mb-2">Access Denied</h2>
          <p className="text-slate-600 mb-6">
            You must accept the Terms of Service and Confidentiality Agreement to use the Perennity Compliance Assessment Tool.
          </p>
          <button
            onClick={() => setShowDeclineMessage(false)}
            className="px-6 py-3 bg-gradient-to-r from-teal-600 to-emerald-600 text-white rounded-xl font-medium hover:from-teal-700 hover:to-emerald-700 transition-colors"
          >
            Review Terms Again
          </button>
        </div>
      </div>
    );
  }

  // Show terms modal if not accepted
  if (!hasAccepted) {
    return <TermsAcceptanceModal onAccept={handleAccept} onDecline={handleDecline} />;
  }

  // User has accepted, show the app
  return children;
};

// ============================================
// TERMS LINK COMPONENT (for footer)
// ============================================

export const TermsLink = ({ className = '' }) => {
  const [showTerms, setShowTerms] = useState(false);

  return (
    <>
      <button
        onClick={() => setShowTerms(true)}
        className={`text-sm text-slate-500 hover:text-teal-600 underline transition-colors ${className}`}
      >
        Terms of Service & NDA
      </button>

      {showTerms && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/80 backdrop-blur-sm p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-3xl w-full max-h-[90vh] flex flex-col overflow-hidden">
            <div className="bg-gradient-to-r from-teal-600 to-emerald-600 px-6 py-4 text-white flex items-center justify-between flex-shrink-0">
              <div className="flex items-center gap-3">
                <FileText className="w-6 h-6" />
                <h2 className="text-lg font-bold">Terms of Service & Confidentiality Agreement</h2>
              </div>
              <button
                onClick={() => setShowTerms(false)}
                className="text-white/80 hover:text-white transition-colors"
              >
                ✕
              </button>
            </div>
            <div className="flex-1 overflow-y-auto px-6 py-4">
              <TermsContent />
            </div>
            <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex-shrink-0">
              <button
                onClick={() => setShowTerms(false)}
                className="w-full px-6 py-3 bg-gradient-to-r from-teal-600 to-emerald-600 text-white rounded-xl font-medium hover:from-teal-700 hover:to-emerald-700 transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

// Default export
export default TermsGate;
